### ISSUE TITLE
`transformedPropertySchema` not working as intended

### ISSUE THREAD

**Issue by xyzqm** [NotWoods/travel#10]
The documentation claims that this alone:
```
properties: z.object({
      // Converts to a primitive string
      Name: transformedPropertySchema.title,
...
```
should be able to convert the title to a primitive string; however, I have to do the following to achieve the desired effect:
```
...
      Name: transformedPropertySchema.title.transform((prop) => prop.title[0].text.content),
...
```
Am I misunderstanding `transformedPropertySchema`?

**Comment by NotWoods** [comment]
Thanks for filing this, I found the source of the bug in a typo. (I'm exporting the wrong module.)

You can work around this using:
```js
import * as transformedPropertySchema from 'notion-astro-loader/schemas/transformed-properties'
```
