### ISSUE TITLE
Supporting images and videos

### ISSUE THREAD

**Issue by xyzqm** [NotWoods/travel#11]
Am I correct in understanding that currently, adding images and videos in a Notion file does not work yet when plugged into Astro? My document looks like this:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/abce50c6-339f-41a4-aa23-540240105d2f">

**Comment by xyzqm** [comment]
Oh nevermind, the image has loaded now...I'm guessing the video will load after some time as well. Although I'm curious---what's the plan for handling image/video assets moving forward? Will they be baked into the site when it's built or kept on the Notion servers?

**Comment by NotWoods** [comment]
I'm planning to pass images to Astro's image service so they get turned into local assets. See https://github.com/NotWoods/travel/pull/9

**Comment by NotWoods** [comment]
0.4.0 will be out soon with support for remote images getting processed with the Astro Asset API.
