### ISSUE TITLE
Dependency conflict with Astro 5.0.0-beta

### ISSUE THREAD

**Issue by bkyerv** [NotWoods/travel#12]
I'm trying to use notion-astro-loader with Astro 5.0.0-beta.12, but running into a peer dependency conflict. The package currently requires Astro ^4.14.0 || ^5.0.0, but doesn't seem to recognize the beta version. Could the peer dependency range be updated to include beta versions of Astro 5?

**Comment by lbineau** [comment]
Starting from Astro 5 is officially out so it is not an issue anymore :-)

**Comment by NotWoods** [comment]
Closing because Astro 5 is out. If you need beta support you can use [overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#overrides).
