### ISSUE TITLE
How do you use images?

### ISSUE THREAD

**Issue by nlnw** [NotWoods/travel#2]
When I use the rendered html for a page with embedded images, the images don't have a src set to a string. Instead it's an [Object object]. How do you use images with this content loader?

**Comment by nlnw** [comment]
It also does not seem to pass through image alignment information. I set an image to align right, but there is nothing in the resulting html that indicates the alignment.

**Comment by nlnw** [comment]
Are you supported to use the metadata field to re-embed the images?

**Comment by NotWoods** [comment]
This is a bug in [notion-rehype-k](https://www.npmjs.com/package/notion-rehype-k?activeTab=readme), I wrote a workaround and I'll look into upstreaming it.

**Comment by NotWoods** [comment]
Published 0.2.0 with this fix!
