### ISSUE TITLE
Feature Request: Provide hooks to handle embeds

### ISSUE THREAD

**Issue by nlnw** [NotWoods/travel#4]
Notion supports embedding iframes like Twitter pages. But often you can't do that directly on a normal site, and instead I would want to provide custom handling for the embed. For example, I might slightly modify the URL, or I want to provide custom HTML to handle the embed. Is this possible?

**Comment by NotWoods** [comment]
You should be able to do that with a rehype plugin to modify the HTML that's generated. It's not something I'm likely to re-implement here
