### ISSUE TITLE
Feature request: save images as base 64 strings

### ISSUE THREAD

**Issue by NoamMuallem** [NotWoods/travel#8]
Because notion assets has expiration time limit (3 hours I think),
all the images links will be good for 3 hours, a good solution for this problem is convert the assets into base 64 strings (or any other light wight string based image encoding).
I sagest maybe add another option in the loader to allow this.

**Comment by NotWoods** [comment]
I've added support for `getImage` using the Astro Asset API which should be sufficient for caching. If this doesn't address your use case we can revisit base64 URLs later and open a new issue.
